package dev.roshana.buildsrc

object Versions {
    const val composeVersion = "1.1.0-beta01"
    const val kotlin = "1.5.31"
    const val gradle = "7.2.2"
    const val activityCompose = "1.4.0"
    const val composeViewModel = "2.4.1"
    const val composePaging = "1.0.0-alpha16"
    const val composeHilt = "1.0.0"
    const val composeNav = "2.5.1"
    const val composeAnimNav = "0.20.2"
    const val arrow = "0.10.4"
    const val kt_lint = "0.37.2"
    const val coroutines = "1.3.3"
    const val coroutinesAdapter = "1.0.0"
    const val gradleVersions = "0.27.0"
    const val hilt = "2.42"
    const val hiltViewModel = "1.0.0-alpha03"
    const val arch = "2.2.0"
    const val archTest = "2.1.0"
    const val material = "1.6.1"
    const val constraintLayout = "1.1.3"
    const val room = "2.4.1"
    const val dagger = "2.25.4"
    const val okHttp = "4.10.0"
    const val gson = "2.8.6"
    const val retrofit = "2.7.1"
    const val stetho = "1.5.1"
    const val glide = "4.11.0"
    const val junit = "4.13.2"
    const val extJunit = "1.1.3"
    const val testRunner = "1.2.0"
    const val espresso = "3.4.0"
    const val mockitoKotlin = "1.6.0"
    const val navigationComponent = "2.3.0"
    const val fragment = "1.2.5"
    const val coreKtx = "1.7.0"
    const val lifeCycle = "2.5.1"
    const val composeActivity = "1.4.0"
    const val kotlinConverter = "0.8.0"
    const val jsonSerialization = "1.3.3"
    const val picasso = "2.8"
    const val coil = "2.2.1"
    const val coilImage = "1.6.1"
}